name: MSBuild

on:
  push:
    paths:
      - 'VRC-OSC-AudioEars/**'  
      - 'Installer/**'  
      - '.github/**'
  pull_request:
    paths:
      - 'VRC-OSC-AudioEars/**'
      - 'Installer/**'
      - '.github/**'
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/cache@v4
      with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2.0.0

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build App
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild VRC-OSC-AudioEars/VRC-OSC-AudioEars.csproj /property:Configuration=Release
    - name: Upload App
      uses: actions/upload-artifact@v4.3.1
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: "VRC-OSC-AudioEars\\bin\\release\\"
        
    - name: Build Installer
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run:  msbuild Installer/Installer.wixproj
      
    - name: Upload Installer
      uses: actions/upload-artifact@v4.3.1
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: "Installer\\bin\\Release\\"
        
